version: "3"
services:
  django:
    build: .
    container_name: muc-back
    ports:
      - "8000:8000"
    volumes:
      - .:/src
      - static_volume:/static
      - media_volume:/media
    restart: always
    command: sh -c "python manage.py makemigrations && python manage.py migrate && gunicorn med_center.wsgi:application --bind 0.0.0.0:8000"
    depends_on:
      - db

  nginx:
    image: nginx
    container_name: muc-nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/static
      - media_volume:/media
    depends_on:
      - django


volumes:
  static_volume:
  media_volume:
